### ISSUE TITLE
Untranslatable app

### ISSUE THREAD

**Issue by ghost** [Hankamotz/xake-chess#1]
Hello,
Could you please make this app translatable?
Thanks for this great work!

**Comment by Hankamotz** [comment]
Hi Anne017, I'll try to continue the development of chess this summer, trying to add some new features and maybe make some translations. If you can collaborate, help is appreciated. Thanks!

**Comment by Hankamotz** [comment]
Hi, the app is ready to translate; please, see the xake.hankamotz.pot file in native-QML branch. Thanks!

**Comment by Hankamotz** [comment]
hi Anne017! I have update .pot file and now need some (few) new translations, if you want translate, 
P.D: There is an issue with utilise[nbsp] in fr.po,
msgid "This app uses:"
msgstr "Cette application utilise[nbsp]:"
 thanks again :)
