### ISSUE TITLE
Error in last update

### ISSUE THREAD

**Issue by wagafo** [Hankamotz/xake-chess#5]
Updating to version 0.5.4 in the BQ Acquaris E5 i get 

Update Failed
ProcesError: 0 - ErrorInProcess
Exit code: 7

Then when trying to update again, the following message shows in the update window of configuration:

Update Failed
HttpError: 401 - UNAUTHORIZED

**Comment by Hankamotz** [comment]
Hi Walter, I think you have some type of account issue to update, try rebooting your device and ensure you are logged to your ubuntu one account

**Comment by wagafo** [comment]
Thanks, after rebooting the update completed fine.
